image: ubuntu:latest

before_script:
  - apt-get update -yqq
  - apt-get install -yqq npm nodejs-legacy git wget

test:
  script:
    - npm install --unsafe-perm=true || true
    - npm run lint:sh
    - npm run lint:md
  artifacts:
    paths:
      - npm-debug.log
    expire_in: 1 month
