#!/usr/bin/env bash
# install: part of the 4U6U57/dotfiles project
# INSTALL: Run this script to install this repo
# Installer script for the dotfiles repo, calls the dotbot utility
# Based off of anishathalye/dotbot

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git pull origin master
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
